social_gaming_homepage:
    path:     /
    defaults: { _controller: SocialGamingBundle:Default:index }

social_gaming_backend:
        path: /frontend/index
        defaults: { _controller: SocialGamingBundle:Frontend:index }

social_gaming_frontend_startFront:
        path: /frontend/startFront
        defaults: { _controller: SocialGamingBundle:Frontend:startFront }
social_gaming_frontend_result:
        path: /frontend/result
        defaults: { _controller: SocialGamingBundle:Frontend:result }
social_gaming_frontendend_impressum:
        path: /frontend/impressum
        defaults: { _controller: SocialGamingBundle:Frontend:impressum }
social_gaming_frontendend_suspect:
        path: /frontend/suspect
        defaults: { _controller: SocialGamingBundle:Frontend:suspect }