social_gaming_login:
        path: /login
        defaults: { _controller: SocialGamingBundle:Security:login }
social_gaming_register:
        path: /frontend/register
        defaults: { _controller: SocialGamingBundle:Registration:register }

social_gaming_backend:
        path: /admin
        defaults: { _controller: SocialGamingBundle:Admin:index }

social_gaming_backend_create_user:
    path: /admin/user/create
    defaults: { _controller: SocialGamingBundle:Admin:createUser }
social_gaming_backend_create_show:
    path: /admin/show/create
    defaults: { _controller: SocialGamingBundle:Admin:createShow }
social_gaming_backend_create_episode:
    path: /admin/episode/create
    defaults: { _controller: SocialGamingBundle:Admin:createEpisode }
social_gaming_backend_create_hint:
    path: /admin/hint/create
    defaults: { _controller: SocialGamingBundle:Admin:createHint }
social_gaming_backend_create_suspect:
    path: /admin/suspect/create
    defaults: { _controller: SocialGamingBundle:Admin:createSuspect }

#FRONTEND

social_gaming_frontend:
        path: /
        defaults: { _controller: SocialGamingBundle:Frontend:index }
social_gaming_frontend_startFront:
        path: /frontend/startFront
        defaults: { _controller: SocialGamingBundle:Frontend:startFront }
social_gaming_frontend_result:
        path: /frontend/result
        defaults: { _controller: SocialGamingBundle:Frontend:result }
social_gaming_frontend_info:
        path: /frontend/info
        defaults: { _controller: SocialGamingBundle:Frontend:info }
social_gaming_frontend_suspect:
        path: /frontend/suspect
        defaults: { _controller: SocialGamingBundle:Frontend:suspect }
social_gaming_frontend_impressum:
        path: /frontend/impressum
        defaults: { _controller: SocialGamingBundle:Frontend:impressum }
social_gaming_frontend_episodes:
        path: /episodes/view/{showId}
        defaults: { _controller: SocialGamingBundle:Frontend:episodesView }
social_gaming_frontend_episode:
        path: /episode/view/{episodeId}
        defaults: { _controller: SocialGamingBundle:Frontend:episodeView }
social_gaming_frontend_afterVoting:
        path: /frontend/afterVoting/{suspectId}
        defaults: { _controller: SocialGamingBundle:Frontend:afterVoting }
social_gaming_frontend_highscore:
        path: /frontend/highscore
        defaults: { _controller: SocialGamingBundle:Frontend:highscore }
social_gaming_frontend_info_1:
        path: /frontend/info_1
        defaults: { _controller: SocialGamingBundle:Frontend:info_1 }
social_gaming_frontend_info_2:
        path: /frontend/info_2
        defaults: { _controller: SocialGamingBundle:Frontend:info_2 }
social_gaming_frontend_register:
        path: /frontend/register
        defaults: { _controller: SocialGamingBundle:Frontend:register }

#ANDROID

social_gaming_android_getHints:
        path: /android/getHints
        defaults: { _controller: SocialGamingBundle:Android:getHints }


#USER

social_gaming_user_login:
        path: /user/login
        defaults: { _controller: SocialGamingBundle:User:login }

social_gaming_user_logout:
        path: /user/logout
        defaults: { _controller: SocialGamingBundle:User:logout }

social_gaming_user_isLoggedIn:
        path: /user/isLoggedIn
        defaults: { _controller: SocialGamingBundle:User:isLoggedIn }

