social_gaming_backend:
        path: /admin
        defaults: { _controller: SocialGamingBundle:Admin:index }

social_gaming_backend_create_user:
    path: /admin/user/create
    defaults: { _controller: SocialGamingBundle:Admin:createUser }
social_gaming_backend_create_show:
    path: /admin/show/create
    defaults: { _controller: SocialGamingBundle:Admin:createShow }
social_gaming_backend_create_episode:
    path: /admin/episode/create
    defaults: { _controller: SocialGamingBundle:Admin:createEpisode }
social_gaming_backend_create_hint:
    path: /admin/hint/create
    defaults: { _controller: SocialGamingBundle:Admin:createHint }
social_gaming_backend_create_suspect:
    path: /admin/suspect/create
    defaults: { _controller: SocialGamingBundle:Admin:createSuspect }

#FRONTEND

social_gaming_frontend:
        path: /
        defaults: { _controller: SocialGamingBundle:Frontend:index }

social_gaming_frontend_startFront:
        path: /frontend/startFront
        defaults: { _controller: SocialGamingBundle:Frontend:startFront }
social_gaming_frontend_result:
        path: /frontend/result
        defaults: { _controller: SocialGamingBundle:Frontend:result }

social_gaming_frontend_suspect:
        path: /frontend/suspect
        defaults: { _controller: SocialGamingBundle:Frontend:suspect }

social_gaming_frontend_impressum:
        path: /frontend/impressum
        defaults: { _controller: SocialGamingBundle:Frontend:impressum }

#ANDROID

social_gaming_android_getHints:
        path: /android/getHints
        defaults: { _controller: SocialGamingBundle:Android:getHints }
