social_gaming_homepage:
    path:     /
    defaults: { _controller: SocialGamingBundle:Default:index }
social_gaming_backend:
        path: /admin
        defaults: { _controller: SocialGamingBundle:Admin:index }
social_gaming_backend_create_user:
    path: /admin/user/create
    defaults: { _controller: SocialGamingBundle:Admin:createUser }
social_gaming_backend_create_show:
    path: /admin/show/create
    defaults: { _controller: SocialGamingBundle:Admin:createShow }
