SocialGamingBundle\Entity\Episode:
    type: entity
    table: episode
    indexes:
        fk_episode_show_idx:
            columns:
                - show_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        startdate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: startDate
        enddate:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: endDate
        summary:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
    manyToOne:
        show:
            targetEntity: Show
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                show_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: episode
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
