SocialGamingBundle\Entity\GameUser:
    type: entity
    repositoryClass: SocialGamingBundle\Repository\UserRepository
    table: gameUser
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        isactive:
            type: boolean
            nullable: true
            column: isActive
        password:
            type: string
            nullable: false
            length: 64
    oneToOne:
        roles:
            targetEntity: Role
            inversedBy: gameUser
            joinColumn:
                name: roleId
                referencedColumnName: id
    lifecycleCallbacks: {  }
