SocialGamingBundle\Entity\Tvshow:
    type: entity
    table: tvshow
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    lifecycleCallbacks: {  }
