SocialGamingBundle\Entity\UserScore:
    type: entity
    table: user_score
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
            column: userId
        score:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
